import React from 'react'

const styles = {
  wrapper: { display: 'flex', flexDirection: 'column', gap: '1.25rem', animation: 'fadeIn 0.3s ease' },
  verdict: {
    textAlign: 'center',
    padding: '2rem 1.5rem',
    borderRadius: 12,
    border: '2px solid',
  },
  verdictLabel: {
    fontSize: '2rem',
    fontWeight: 800,
    letterSpacing: '0.05em',
    marginBottom: '0.5rem',
  },
  confidenceRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    marginTop: '0.5rem',
  },
  confidenceValue: { fontSize: '1.1rem', fontWeight: 600 },
  barBg: {
    width: 160,
    height: 8,
    background: '#2e3249',
    borderRadius: 4,
    overflow: 'hidden',
  },
  section: {
    background: 'var(--color-surface-alt)',
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    padding: '1rem 1.25rem',
  },
  sectionTitle: {
    fontSize: '0.82rem',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--color-text-muted)',
    marginBottom: '0.75rem',
  },
  featureRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '0.5rem',
  },
  featureWord: {
    fontSize: '0.9rem',
    fontWeight: 500,
    minWidth: 90,
    color: 'var(--color-text)',
  },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '0.75rem',
  },
  metaCard: {
    background: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    padding: '0.6rem 0.8rem',
  },
  metaLabel: { fontSize: '0.75rem', color: 'var(--color-text-muted)', marginBottom: 2 },
  metaValue: { fontSize: '0.95rem', fontWeight: 600 },
}

function ConfidenceBar({ value, color }) {
  return (
    <div style={styles.barBg}>
      <div style={{ width: `${value}%`, height: '100%', background: color, borderRadius: 4, transition: 'width 0.6s ease' }} />
    </div>
  )
}

function FeatureBar({ feature, weight }) {
  const isPositive = weight > 0
  const pct = Math.min(Math.abs(weight) * 400, 100)
  return (
    <div style={styles.featureRow}>
      <span style={styles.featureWord}>"{feature}"</span>
      <div style={{ flex: 1, height: 6, background: '#2e3249', borderRadius: 3, overflow: 'hidden' }}>
        <div style={{
          width: `${pct}%`,
          height: '100%',
          background: isPositive ? 'var(--color-fake)' : 'var(--color-real)',
          borderRadius: 3,
        }} />
      </div>
      <span style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', minWidth: 40, textAlign: 'right' }}>
        {weight > 0 ? '+' : ''}{weight.toFixed(3)}
      </span>
    </div>
  )
}

export default function ResultPanel({ result }) {
  if (!result) return null

  const isFake = result.label === 'Fake'
  const color = isFake ? 'var(--color-fake)' : 'var(--color-real)'
  const bg = isFake ? 'var(--color-fake-bg)' : 'var(--color-real-bg)'
  const features = result.explanation?.top_features || []
  const summary = result.explanation?.summary || ''

  return (
    <div style={styles.wrapper}>
      {/* Verdict */}
      <div style={{ ...styles.verdict, borderColor: color, background: bg }}>
        <div style={{ ...styles.verdictLabel, color }}>{result.label.toUpperCase()} NEWS</div>
        <div style={styles.confidenceRow}>
          <span style={{ ...styles.confidenceValue, color }}>
            {result.confidence}% confidence
          </span>
          <ConfidenceBar value={result.confidence} color={color} />
        </div>
        {result.low_confidence && (
          <div style={{
            marginTop: '0.75rem',
            padding: '0.4rem 0.8rem',
            background: '#2d1a00',
            borderRadius: 6,
            color: 'var(--color-warn)',
            fontSize: '0.85rem',
            display: 'inline-block',
          }}>
            ⚠ Low confidence — manual verification recommended
          </div>
        )}
      </div>

      {/* Explanation */}
      {(summary || features.length > 0) && (
        <div style={styles.section}>
          <div style={styles.sectionTitle}>Explanation</div>
          {summary && (
            <p style={{ fontSize: '0.9rem', color: 'var(--color-text-muted)', marginBottom: features.length ? '1rem' : 0 }}>
              {summary}
            </p>
          )}
          {features.map((f, i) => (
            <FeatureBar key={i} feature={f.feature} weight={f.weight} />
          ))}
          <p style={{ fontSize: '0.76rem', color: 'var(--color-text-muted)', marginTop: '0.5rem' }}>
            Feature importance generated by LIME (Local Interpretable Model-Agnostic Explanations).
            Positive weights indicate terms associated with Fake News; negative with Real News.
          </p>
        </div>
      )}

      {/* Meta */}
      <div style={styles.section}>
        <div style={styles.sectionTitle}>Analysis Details</div>
        <div style={styles.metaGrid}>
          <div style={styles.metaCard}>
            <div style={styles.metaLabel}>Model</div>
            <div style={styles.metaValue}>{result.model_used}</div>
          </div>
          <div style={styles.metaCard}>
            <div style={styles.metaLabel}>Input Type</div>
            <div style={styles.metaValue} style={{ textTransform: 'capitalize' }}>
              {result.input_type}
            </div>
          </div>
          <div style={styles.metaCard}>
            <div style={styles.metaLabel}>Word Count</div>
            <div style={styles.metaValue}>{result.word_count?.toLocaleString()}</div>
          </div>
          <div style={styles.metaCard}>
            <div style={styles.metaLabel}>Processing Time</div>
            <div style={styles.metaValue}>{result.processing_time_ms} ms</div>
          </div>
        </div>
      </div>
    </div>
  )
}
